<a href="https://colab.research.google.com/github/DavoodSZ1993/RL/blob/main/03_Q_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

In [21]:
q = np.matrix(np.zeros([6,6])) # a 6x6 matrix for Q-values

# Reward
r = np.matrix([[-1,-1,-1,-1,0,-1],
               [-1,-1,-1,0,-1,100],
               [-1,-1,-1,0,-1,-1],
               [-1,0,0,-1,0,-1],
               [0,-1,-1,0,-1,100],
               [-1,0,-1,-1,0,100]])

gamma = 0.8
epsilon = 0.4

possible_actions = []
possible_q=[]

for state in range(6):
  for action in range(6):
    if r[state,action]>=0:
      possible_actions.append(action)
      possible_q.append(q[state, action])

possible_actions, possible_q

([4, 3, 5, 3, 1, 2, 4, 0, 3, 5, 1, 4, 5],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])

In [13]:
q = np.matrix(np.zeros([6,6])) # a 6x6 matrix for Q-values

# Reward
r = np.matrix([[-1,-1,-1,-1,0,-1],
               [-1,-1,-1,0,-1,100],
               [-1,-1,-1,0,-1,-1],
               [-1,0,0,-1,0,-1],
               [0,-1,-1,0,-1,100],
               [-1,0,-1,-1,0,100]])

gamma = 0.8
epsilon = 0.4

for episode in range(101):
  # Random intial state
  state = np.random.randint(0,6)

  # if not final state:
  while(state!=5):
    # choose a possible action
    # Even in random case, we cannot choose actions whose r[state,action]=-1
    possible_actions = []
    possible_q=[]

    for action in range(6):
      if r[state,action]>=0:
        possible_actions.append(action)
        possible_q.append(q[state, action])

    # Step next state, here we use epsilon-greedy algorithm.
    action = -1
    if np.random.random() < epsilon:
      # choose a random action
      action = possible_actions[np.random.randint(0, len(possible_actions))]

    else: 
      # Greedy
      action = possible_actions[np.argmax(possible_q)]

    # update Q-value
    q[state, action] = r[state,action] + gamma * q[action].max()

    # Go to the next state

    state = action

    # Display Training Progress
    if episode %10 ==0:
      print("------------------------------------------------------")
      print("Training episode:%d"%episode)
      print(q)

------------------------------------------------------
Training episode:0
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
------------------------------------------------------
Training episode:0
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
------------------------------------------------------
Training episode:0
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
------------------------------------------------------
Training episode:0
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
------------------------------------------------------
Training episode:0
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 

In [24]:
np.random.random()

0.46443429912273615